// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package alert

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Alert struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Symbol      string
	TargetPrice string
	Direction   string
	Active      bool
	CreatedAt   sql.NullTime
}

type TriggeredAlert struct {
	ID             uuid.UUID
	AlertID        uuid.UUID
	TriggeredPrice string
	CreatedAt      time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
}
