// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package alert

import (
	"context"

	"github.com/google/uuid"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (user_id,symbol,target_price,direction)
VALUES ($1,$2,$3,$4)
RETURNING id, user_id, symbol, target_price, direction, active, created_at
`

type CreateAlertParams struct {
	UserID      uuid.UUID
	Symbol      string
	TargetPrice string
	Direction   string
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, createAlert,
		arg.UserID,
		arg.Symbol,
		arg.TargetPrice,
		arg.Direction,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symbol,
		&i.TargetPrice,
		&i.Direction,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createTriggeredAlert = `-- name: CreateTriggeredAlert :one
INSERT INTO triggered_alerts (alert_id, triggered_price)
VALUES ($1, $2)
RETURNING id, alert_id, triggered_price, created_at
`

type CreateTriggeredAlertParams struct {
	AlertID        uuid.UUID
	TriggeredPrice string
}

func (q *Queries) CreateTriggeredAlert(ctx context.Context, arg CreateTriggeredAlertParams) (TriggeredAlert, error) {
	row := q.db.QueryRowContext(ctx, createTriggeredAlert, arg.AlertID, arg.TriggeredPrice)
	var i TriggeredAlert
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.TriggeredPrice,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAlert = `-- name: DeactivateAlert :exec
UPDATE alerts SET active = false WHERE id = $1
`

func (q *Queries) DeactivateAlert(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateAlert, id)
	return err
}

const deleteAlert = `-- name: DeleteAlert :exec
DELETE FROM alerts WHERE id = $1
`

func (q *Queries) DeleteAlert(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAlert, id)
	return err
}

const getActiveAlertsBySymbol = `-- name: GetActiveAlertsBySymbol :many
SELECT id, user_id, symbol, target_price, direction, active, created_at FROM alerts WHERE symbol = $1 AND active = true
`

func (q *Queries) GetActiveAlertsBySymbol(ctx context.Context, symbol string) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, getActiveAlertsBySymbol, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symbol,
			&i.TargetPrice,
			&i.Direction,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveAlerts = `-- name: GetAllActiveAlerts :many
SELECT id, user_id, symbol, target_price, direction, active, created_at FROM alerts WHERE active = true
`

func (q *Queries) GetAllActiveAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symbol,
			&i.TargetPrice,
			&i.Direction,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByUser = `-- name: ListAlertsByUser :many
SELECT id, user_id, symbol, target_price, direction, active, created_at FROM alerts WHERE user_id = $1
`

func (q *Queries) ListAlertsByUser(ctx context.Context, userID uuid.UUID) ([]Alert, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symbol,
			&i.TargetPrice,
			&i.Direction,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
